### ISSUE TITLE
Missing "TetDis.dis" file

### ISSUE THREAD

**Issue by kylekam** [ZhengMianlun/deep_emulator#2]
Hi, I'm trying to run test.py but the code isn't able to compile when animationTet2Surface.py searches for "TetDis.dis". I looked around for "TetDis.dis" in the repo but I wasn't able to find any file with that name. Is this a typo?

**Comment by ZhengMianlun** [comment]
Hi, "TetDis.dis" is computed and saved in animationTet2Surface.py, line 31. If your code didn't find the file, the reason might be the utility "textMatrix2Matrix" didn't convert TetDis_txt.dis to TetDis.dis successfully.

**Comment by kylekam** [comment]
The specific error that I'm getting that I believe to have originated from this line is "OSError: [WinError 193] %1 is not a valid Win32 application". A screenshot of the error is attached in this link: [https://i.imgur.com/t5pBIre.png](https://i.imgur.com/t5pBIre.png)

**Comment by ZhengMianlun** [comment]
Seems you need to compile the two utilities. please refer to deep_emulator/code/vega_FEM/README.md

**Comment by kylekam** [comment]
I was able to compile the two utilities, but now it says that the 'input_SurfaceDis.u' file is missing. Is this still related to compiling the two files? Here's a screenshot of the error: [https://i.imgur.com/VyYDPxG.png](https://i.imgur.com/VyYDPxG.png)

**Comment by ZhengMianlun** [comment]
the file is created by animationTet2Surface

**Comment by kylekam** [comment]
I had accidentally deleted a variable which misplaced where some of the files were saved, thanks!

**Comment by kylekam** [comment]
Hi, I tried running the code from a clean install of Ubuntu and I believe I'm getting the same error. I have not touched any of the code files. The error I'm getting is below. I've tried re-downloading the files multiple times.
```
kyle@kyle-pc:~/Research/deep_emulator-main/code$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 170, in <module>
    predict_rollout(net, frame_num = frames, mesh_path_root = mesh_path, data_path_root = input_path, eval_path_root = eval_path, flag = "surface", character_name = character_name, camera_set = camera_set)
  File "test.py", line 134, in predict_rollout
    surface_input_dis = loadData_Float(os.path.join(eval_path_root, "input_SurfaceDis.u"))
  File "test.py", line 19, in loadData_Float
    data = np.fromfile(filename, dtype=np.float64)
FileNotFoundError: [Errno 2] No such file or directory: './weight/eval/michelle/cross_jumps/input_SurfaceDis.u'
```

**Comment by yuanzheliu-ucsb** [comment]
input_SurfaceDis.u is created by animationTet2Surface. please check if the function animationTet2Surface runs correctly.

**Comment by ZhengMianlun** [comment]
input_SurfaceDis.u is created by animationTet2Surface. please check if the function animationTet2Surface runs correctly.

**Comment by kylekam** [comment]
It turns out there were some weird permission errors with the executables not being allowed to write on my computer.
